title: "Art's developer blog"
author: "Artyom Schedrov"
description: "Some short description of your blog can go here." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "art.worknsk@mail.com"
#twitter_username: "twitteruser"
github_username: "artschedrov"
linkedin_username: "artyom-schedrov-257266230"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

# rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: false
    
plugins:
  - jekyll-sitemap
  
home_post_limit: 5  

titles_from_headings:
  strip_title: true
  collections: true
  
# The github repo that is to be used for looking up comments
comments_repo: artschedrov/artschedrov.github.io 

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
